#ifndef ISR80H_H
#define ISR80H_H

enum ISR80H_COMMANDS
{
    ISR80H_COMMAND1_PRINT,
    ISR80H_COMMAND2_GETKEY,
    ISR80H_COMMAND3_PUTCHAR,
    ISR80H_COMMAND4_MALLOC,
    ISR80H_COMMAND5_FREE,
    ISR80H_COMMAND6_PROCESS_LOAD_START
};

void isr80h_register_commands();

#endif
